services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
            - ./laravel.conf:/etc/apache2/sites-available/000-default.conf

        depends_on:
            - db

    db:
        image: nouchka/sqlite3
        volumes:
            - ./database/database.sqlite:/db/sqlite.db
        environment:
            SQLITE_DATABASE: /db/sqlite.db
